### ISSUE TITLE
Ubiquity meta account

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#1]
https://github.com/orgs/ubiquity/discussions/43

**Comment by 0x4007** [comment]
These discussions should be transferred to this research repository.

**Comment by sergfeldman** [comment]
> These discussions should be transferred to this research repository.

I tried in many ways, but when I try to transfer the discussion, the resource repository does not go.
![Not found repo](https://github.com/ubiquity/research/assets/15567379/fd6d2ffe-2405-46d9-9b99-27c406205f52)
![Not found repo 2](https://github.com/ubiquity/research/assets/15567379/8ab772e0-2186-4294-9c60-663ee7f77313)

**Comment by sergfeldman** [comment]
> These discussions should be transferred to this research repository.

Transferred to the Research repository https://github.com/ubiquity/research/discussions/13
