### ISSUE TITLE
Review other bounty providers on GitHub and aggregate

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#10]
https://github.com/orgs/ubiquity/discussions/74

**Comment by 0x4007** [comment]
I think that "drafts" should be in "discussions" and then only converted into issues when its time to execute (UbiquiBot can interact with issues, and currently does not with discussions.)

**Comment by sergfeldman** [comment]
> I think that "drafts" should be in "discussions" and then only converted into issues when its time to execute (UbiquiBot can interact with issues, and currently does not with discussions.)

I created a separate discussion for this topic, and also removed the word DRAFT from all issues on the Research board

**Comment by 0x4007** [comment]
Oh I'm learning here: the project board can't display discussions? It intuitively seems cleaner to me if we use issues strictly for execution and discussions for research and early ideas.

@sergfeldman can you figure a way to make that work?

**Comment by sergfeldman** [comment]
> Oh I'm learning here: the project board can't display discussions? It intuitively seems cleaner to me if we use issues strictly for execution and discussions for research and early ideas.
> 
> @sergfeldman can you figure a way to make that work?

@pavlovcik Yes, will look for a solution

**Comment by 0x4007** [comment]
Just don't turn it into an issue. I made some conversation topics and see that you can leave it as a literal draft. These conversation points need to be turned into either drafts or remade.
