### ISSUE TITLE
Prototype AI assistant in Emma closed beta

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#101]
I applied to the Emma closed beta https://getemma.ai/ some time ago.
>Create an AI-powered assistant in minutes!
Quickly build a custom AI assistant powered by OpenAI's GPT-3.5 technology! Connect it to your organization's resources or upload your files, empowering the assistant to assist with any inquiries you or your team may encounter.

An example of the assistant for Engineering can be found
https://getemma.ai/examples

Answering their questions I mentioned that we need integrations with GitHub and potentially Google sheets. 
Also, they have more integrations https://getemma.ai/integrations

I can share Emma beta testing credentials in the dm.

The invitation
>Welcome to the Emma beta program!
You can sign in to your account using the credentials below.
Once signed in, you will be able to create your assistants and connect your data sources.
Note: Only a handful of integrations are available to publicly add. Other integrations are currently in development, and can be added to your account upon request.
Our team is available to answer any questions or to help you with the set-up and improvement of your assistants. You can reach us via email: beta@getemma.ai
Note that the integrations you mentioned are not currently available publicly.
We can add Google sheets to your account in the coming weeks on request.
Thanks for being part of our beta, your input helps us improve before the public launch.
The Emma onboarding team

An AI assistant can effectively onboard new bounty hunters and help bounty hunters to select bounties.
In addition, AI assistants can be part of the delivery for our partners as an AI-powered repository manager.

@pavlovcik @rndquu @0xcodercrane  @wannacfuture @whilefoo @web4er @seprintour @devpanther @Steveantor who is interested in creating AI assistants for Ubiquity and our partners? :)

**Comment by rndquu** [comment]
@Keyrxng might be interested in applying the Emma tool to the bot keeping in mind 2 newly introduced bot's commands `/ask` and `/review`

**Comment by Keyrxng** [comment]
> @Keyrxng might be interested in applying the Emma tool to the bot keeping in mind 2 newly introduced bot's commands `/ask` and `/review`

I'm all over this!

You wanna shoot me a dm on telegram or something?

**Comment by rndquu** [comment]
> > @Keyrxng might be interested in applying the Emma tool to the bot keeping in mind 2 newly introduced bot's commands `/ask` and `/review`
> 
> I'm all over this!
> 
> You wanna shoot me a dm on telegram or something?

If you have any ideas of how the Emma tool can make the bot better then you can open an issue in the bot's repo so we could describe all of the details there

P.S. If you need Emma tool credentials pls ask @sergfeldman for them

**Comment by sergfeldman** [comment]
I shared access to Emma for Keyrxng.
He shared me [Superagi](https://superagi.com/) that looks better.

I propose to close as not planned the task to prototype an AI assistant specifically in Emma.
