### ISSUE TITLE
Analyze cooperation with Gnosis Name Service

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#102]
### Intro

@pavlovcik @Draeieg Gnosis just launched Gnosis Name Service a few days ago.

Gnosis Name Service 
https://www.gns.exchange/

The features
- DNS Resolution	
- Multichain	
- Decentralized Architecture	
- Multiple Domains
https://docs.gns.exchange/docs/differences

They have an ambitious roadmap
https://docs.gns.exchange/docs/roadmap

>At GNS, we are continuously seeking exciting partnerships to enhance and expand the possibilities of our platform. Contact us on Twitter and embark on a journey of collaboration.
What We Bring to the Table:
Special Domains: Stand out from the crowd with unique and personalized domains tailored specifically for our esteemed partners. Leave a lasting impression on your audience and establish a distinct online presence.
Social Media Exposure: Expand your reach and amplify your brand's visibility with our dedicated social media exposure. Through our extensive networks and channels, we will showcase your partnership, driving engagement and attracting a wider audience.
Technical Insights: Gain exclusive access to in-depth technical insights and expert guidance from our experienced team. Stay ahead of the curve with cutting-edge knowledge and leverage our expertise to enhance your own technical capabilities.
Part in Future Token Allocations for the GNS DAO: As a partner, you will have the unique opportunity to participate in future token allocations for the GNS Decentralized Autonomous Organization (DAO). Benefit from the growth and success of our ecosystem while actively shaping its future.
https://docs.gns.exchange/docs/contribute

### Proposal

Discuss abilities for cooperation 

- Offer DevPool marketplace? (to develop GNS)

- Use GNS domains for marketing purposes for bounty hunters? (give free domain names linked to GitHub accounts)

- Offer value-added services with AI? (ChatGPT name generator, domain trends watch, etc)

**Comment by Draeieg** [comment]
will add more stuff here as I read


<img width="452" alt="image" src="https://github.com/ubiquity/research/assets/88983138/c5ba8559-a3f1-44b1-9d4b-36a8754ec20e">

None of the big/official gnosis accounts follow them (unlike [gnosis pay](https://twitter.com/gnosispay) by example)

are you sure they're an officially endorsed project or just a community led random thing?

**Comment by sergfeldman** [comment]
> are you sure they're an officially endorsed project or just a community led random thing?

@Draeieg Good question! 

I found out info about their launch from the official Gnosis channel. But they are not actively promoted there.

**Comment by 0x4007** [comment]
Just bought a domain. I tried their dApp and I definitely get 

> community led random thing

vibes. 

When you try changing your wallet you see that its a yam/sushi fork on the UI. Not very official Gnosis vibes at all. 

<img width="501" alt="image" src="https://github.com/ubiquity/research/assets/4975670/70809c18-282d-4c0f-8a56-3360c04a06d6">

Definitely don't think its worth investing into.

**Comment by sergfeldman** [comment]
> Definitely don't think its worth investing into.

@pavlovcik @Draeieg Thanks for the quick check!
I am closing this task as completed since the analysis has been done and a decision has been made.

**Comment by 0x4007** [comment]
> > Definitely don't think its worth investing into.
> 
> 
> 
> @pavlovcik @Draeieg Thanks for the quick check!
> 
> I am closing this task as completed since the analysis has been done and a decision has been made.

We're pretty close to shipping the feature where we can collect comment incentives even on non-bounties
