### ISSUE TITLE
Fill out the form to get GitHub Accelerator updates

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#112]
### Intro

We are looking for cooperation with GitHub.
One of the opportunities is GitHub Accelerator.
https://accelerator.github.com/application

>Applications for the second cohort will open in early 2024. 

### Activity

Fill out the [form](https://docs.google.com/forms/d/e/1FAIpQLSdyDrdKR7JjE_cf-2e5kfrz9PXt_YcKLwLjHoCcyt1OOSghag/viewform) to get GitHub Accelerator updates.

@pavlovcik please, check our answers in the PR so that I can submit the form.

**Comment by 0x4007** [comment]
Ah I need to clear the old priority labels.

**Comment by sergfeldman** [comment]
@pavlovcik Thank you for the quick review!
The form has been submitted.

**Comment by sergfeldman** [comment]
Thank you! 
Claimed both Task Assignee Reward and Task Creator Reward
