### ISSUE TITLE
Preparation for series A funding - research competitors 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#124]
VCs will research competitors before investing so we should be prepared.

One of the competitors

>Enhancing the sustainability of open-source software
The tea Protocol is a decentralized technology framework secured by reputation and incentives that enables open-source developers & maintainers to be rewarded for their software contributions.
https://tea.xyz/learn/overview

>The ranking algorithm for open-source software
Proof of Contribution measures the value, position, and impact of open-source software projects. The ranking algorithm is engineered to bring fairness and equitable rewards to the OSS ecosystem.
https://tea.xyz/learn/proof-of-contribution

https://github.com/teaxyz 3K followers, no Open Source code

Useful links
https://tea.xyz/oss-dev/how-does-it-work 
https://tea.xyz/learn/roadmap

**Comment by pavlovcik** [comment]
This is pretty insane. Good find.

**Comment by pavlovcik** [comment]
@sergfeldman as a heads up I closed this as complete to test our updated comment incentives tech. 

- It didn't include yours because your wallet isn't currently registered in our new database (I will migrate all of the wallet data soon.)
- Looks like it broke on evaluating the relevance of my comment probably due to its length. We need a more robust approach. 
- It would be helpful to link to the [GitHub Action run](https://github.com/ubiquibot/comment-incentives/actions/runs/7693245744/job/20961611371) while we wait for results.

**Comment by sergfeldman** [comment]
> This is pretty insane. Good find.

@pavlovcik Wow, you wrote such a detailed analysis of the competitor! I'm glad you liked the find.

**Comment by sergfeldman** [comment]
@pavlovcik Not sure the project is still maintained, but the logic in the code might be interesting https://github.com/sourcecred

**Comment by pavlovcik** [comment]
> @pavlovcik Not sure the project is still maintained, but the logic in the code might be interesting https://github.com/sourcecred

Looks like they shut down the crypto side. Everybody in the community returned their "grain" in April of 2022 according to their analytics

https://cred.sourcecred.io/#/explorer

I just realized that we could probably approach all of their contributors on their leaderboard to contribute to the DevPool once our updated infrastructure is more stable again. 

It is not clear to me what happened with them. They still retweet stuff, and there are some folks receiving cred still as of last week. Perhaps its now a side project of a couple of developers. I assume they don't have resources to scale this.

**Comment by sergfeldman** [comment]
> @sergfeldman as a heads up I closed this as complete to test our updated comment incentives tech.
> 
> * It didn't include yours because your wallet isn't currently registered in our new database (I will migrate all of the wallet data soon.)
> * Looks like it broke on evaluating the relevance of my comment probably due to its length. We need a more robust approach.
> * It would be helpful to link to the [GitHub Action run](https://github.com/ubiquibot/comment-incentives/actions/runs/7693245744/job/20961611371) while we wait for results.
> * I am waiting to merge a pull request from whilefoo to fix the permit encoding format in the link (it requires a few small adjustments.)

@pavlovcik The bounty was not received due to technical issues.
Is it possible to get it?

**Comment by pavlovcik** [comment]
> ```diff
> ! Permit already posted
> ```

I've actually never seen this before in the latest version.

**Comment by pavlovcik** [comment]
As a heads up there is a bug with the relevance scoring not being applied right now.

**Comment by sergfeldman** [comment]
Thank you, claimed.
