### ISSUE TITLE
Growth Hacking Case Study: ChainGPT

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/research#139]
Stumbled upon https://www.chaingpt.org/ and I think their growth strategy is insane. I am highly, highly skeptical about their technology but looking at the way the company and the founder presents himself is top notch for a new startup. 

What really put me over the edge for being impressed was the "as seen on" section on their homepage. They have linked proof of real tweets and press releases from respected names about their project. 

I think we should study them. 

### Deliverable

Outline everything they did from launch to now. Make a plan and then we can replicate it in the form of GitHub tasks under a new repo.

**Comment by 0x4007** [comment]
I think we should start putting together a more formal marketing plan in the form of GitHub issues. I fear that because I have so many things on my plate now I will forget about this. Would you be able to start with a meta issue in this repository? We can make a dedicated repository later.

**Comment by sergfeldman** [comment]
> I think we should start putting together a more formal marketing plan in the form of GitHub issues.

@pavlovcik Yes, I was going to document our vision for the marketing so we could discuss it with a marketing agency.
The draft structure can be viewed here https://github.com/ubiquity/research/issues/142

**Comment by sergfeldman** [comment]
Thank you!!! Claimed
