### ISSUE TITLE
DAOs as legal entities

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#144]
@pavlovcik  FYI  a16z about a new law to recognize DAOs
https://a16zcrypto.com/posts/article/duna-for-daos/

> Wyoming passed a new law to recognize DAOs as legal entities — enabling such blockchain networks to operate within the bounds of applicable laws, and without compromising their decentralization. This is a major breakthrough as it will provide DAOs with much-needed protections and empower them to keep blockchain networks open.

>Wyoming has a long history of supporting innovative legal entity structures: The state was the first to adopt the limited liability company (LLC); the first to adopt the unincorporated nonprofit association (UNA); and the first to introduce a subset of its LLC statute to be utilized by DAOs. The new Wyoming law incorporates many of the provisions we proposed in model legislation.

>Since this new entity structure is likely to become the industry standard for blockchain networks created in the United States, here’s everything you need to know about Wyoming’s Decentralized Unincorporated Nonprofit Association (DUNA). It answers questions such as why DAOs need it; non-profit vs. for-profit; securities and tax law implications; and other FAQs.

**Comment by 0x4007** [comment]
I was looking to create a Wyoming entity for card issuance but looks like we're some time away from issuing debit cards still.
