### ISSUE TITLE
Uniswap Hook Incubator

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#146]
@pavlovcik FYI Uniswap Hook Incubator  
The first cohort kicks off on April 8. The deadline to apply for the first cohort is March 29.
https://atrium.academy/uniswap#community
https://atriumacademy.typeform.com/to/kk2vFQ4F?typeform-source=atrium.academy 

---

The invitation

As the Uniswap Protocol continues to evolve, UF is dedicated to ensuring devs have the resources to advance alongside it. To facilitate this, we're happy to unveil our latest funded initiative: [the Uniswap Hook Incubator, powered by Atrium Academy](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=ff4c2db77f&e=a1c0dceb7a).This 8-week intensive program is designed to teach experienced DeFi developers how to build hooks– helping you unlock Uniswap v4's full potential. [Check out our full blog post on the initiative](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=2357249653&e=a1c0dceb7a).

What are Hooks?

Uniswap v4 introduces "hooks", which are programmable functions that execute during specific points in a pool’s lifecycle to empower users with customizable tradeoff decisions. We believe the expansive design possibilities for hooks will drive quicker and more secure innovation in DeFi.

About the Hook Incubator

Combining the spirit of a hackathon with a structured cohort-based approach, the program is tailored to guide Solidity developers through the intricacies of launching a hook. Over the span of 8 weeks, participants commit 10 hours per week to learn about essential topics including liquidity operators, dynamic fees, custom accounting, NoOp, periphery contracts and more. The program culminates in a Capstone project, where developers apply their acquired knowledge in crafting their hooks.

Learn from Industry Experts

The program facilitates opportunities to learn directly from the industry’s greatest protocol engineers, leader’s from Uniswap Foundation and Labs, and crypto-native investors through talks, AMAs, and office hours where you can share your work and get feedback.

[William Pote](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=ff36d228d1&e=a1c0dceb7a) - Director of Engineering at Uniswap Labs 

[Tyllen Bicakcic](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=027fa6a316&e=a1c0dceb7a) - Developer Relations Lead at Uniswap Foundation 

[Saucepoint](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=d5ad942992&e=a1c0dceb7a) - Developer Relations Engineer at Uniswap Foundation 

[Aiden](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=036a4537e6&e=a1c0dceb7a) - Developer Relations Engineer at Uniswap Foundation 

[Anirudh Pai ](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=fb77527d6b&e=a1c0dceb7a)- Investor at Dragonfly Capital

[Derek Walkush](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=2496b2649f&e=a1c0dceb7a) - Investor at Variant Fund

[Porter Smith](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=a979dc79be&e=a1c0dceb7a) - Investor at a16z

[Nikhil Raman](https://uniswapfoundation.us21.list-manage.com/track/click?u=98f9e59d1df2b6e1f3e86cee4&id=bb2465af4a&e=a1c0dceb7a) - Investor at Union Square Ventures

Apply Today!

Uniswap Foundation’s grant to Atrium Academy covers tuition for hundreds of qualified developers. If you're ready to explore the endless possibilities of Uniswap v4 hooks and make hook history, sign up now to secure your spot. The first cohort kicks off on April 8. **The deadline to apply for the first cohort is March 29.**

**Comment by 0x4007** [comment]
Don't think this is applicable to our strategic objectives
