### ISSUE TITLE
Suitable tuning of DevPool settings for DevPool partners

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#18]
There are some DevPool settings that DevPool partners may want to tune for their purposes  (bounty pricing, payment, etc).

It would be good to define the vision on
- How new DevPool partners can review all available settings.
- How DevPool partners can tune these options to fit their purposes.

**Comment by 0x4007** [comment]
We currently already support this in the `.github/ubiquibot-config.yml` that is added to their repos. Here's an [example](https://github.com/ubiquity/ubiquibot/blob/development/.github/ubiquibot-config.yml).

**Comment by sergfeldman** [comment]
@pavlovcik Thank you for the link!
