### ISSUE TITLE
Define integration of Ubiquity and DevPool

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#2]
### Background

As discussed in the Research meeting in May 2023, we should explore the integration of Ubiquity and DevPool.

One of the goals is to find relevant use cases for uAD. The more relevant use cases for uAD the better.

**Areas of integration**
- The main area of integration is Ubiquity provides tokens and DevPool creates use cases. 
- One more area of integration is Ubiquity is one of the projects that use DevPool. 

**Non-direct use cases will be defined later:**
- Gamification 
- Ponzi and gambling 
- Marketplace of perks and additional benefits for bounty hunters 
- And others

### uAD
To serve as money for bounty economics.

**For projects**

-  Buy uAD.
Through pools supported by Ubiquity.

- Mint uAD.
The description TBD.

- Top up the wallet to pay uAD bounty hunters for the solved bounties.
The payment is performed automatically with the UbiquiBot flow.

- Pay uAD to Ubiquity for premium DevPool services.
For example, extended bot features, and AI bounty-developer matchmaking.

**For bounty hunters, for project's users**
- Get uAD for the solved bounties.

- Get uAD for filing bugs to the GitHub project.
A bug bounty program.

- Sell uAD.
Through pools supported by Ubiquity.

- Voting to prioritize the resolution of particular bounties by your uAD balance.
This is a feature for community engagement and delivery planning.
The more uAD user has the sooner this bounty should be solved. 

- Buy UBQ for uAD.
Through pools supported by Ubiquity.

### uCR
To incentive bounty creators.

**For projects**
- Pay uCR to bounty creators for the support of bounties resolution.

Bounty creators can get uCR for supporting bounty hunters in bounty resolution that resulted in a successful bounty completion on time.
Bounty creators can provide a clear description, facilitate resolution by answering questions, perform reviews quickly, etc.

- Exchange uCR to uAD.
Through methods supported by Ubiquity.

### UBQ 
To incentivize bounty turnover.

**For projects**
- Get UBQ bonus for creating bounties that are effectively solved.
This is a UBQ bonus for the effective bounty resolution.

- Get UBQ bonus for creating more bounties in the next months.
The project's budget for bounties in May should be more than the project's budget for bounties in April, etc.

- Sell UBQ to get uAD.
Through pools supported by Ubiquity.

**For project's users**
- Lock UBQ for voting to prioritize the resolution of particular bounties.
This is a feature for community engagement and delivery planning.
The more UBQ users locked up for the particular bounty the sooner it should be solved. 

Alex: do not lock UBQ but track an average of the balance of tokens 

- Buy UBQ for uAD.
Through pools supported by Ubiquity.

**Comment by sergfeldman** [comment]
With the DevPool the Ubiquity tokens can get another utility than it was planned before.

uAD - stablecoin for Web3 development.
Help the entire ecosystem grow and get paid.

uCR - fair cashback coin.
Bring more value to the Open Source development - get higher discounts on the paid services.

UBQ - governance of the DeFi for the bonus programs.
Farm yield on your bonus points.

**Comment by 0x4007** [comment]
This doesn't look like a project specification so it should not be an issue.
