### ISSUE TITLE
Legal structure for Ubiquity

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#3]
https://github.com/orgs/ubiquity/discussions/59

**Comment by 0x4007** [comment]
These discussions should be transferred to this research repository. As per my other [comment](https://github.com/ubiquity/research/issues/10#issuecomment-1570380191) it could make sense to create a new draft on the Research project table and populate the draft body with the contents of these discussions. 

Alternatively, the discussions should at least be moved to this research repository if they are being referenced like this.

**Comment by sergfeldman** [comment]
> These discussions should be transferred to this research repository. As per my other [comment](https://github.com/ubiquity/research/issues/10#issuecomment-1570380191) it could make sense to create a new draft on the Research project table and populate the draft body with the contents of these discussions.
> 
> Alternatively, the discussions should at least be moved to this research repository if they are being referenced like this.

This discussion was transferred to the Research repository
https://github.com/ubiquity/research/discussions/14
