### ISSUE TITLE
compound grant 

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/research#36]
I am looking at compound. Thinking what's a simple and useful hook.
https://docs.google.com/document/d/1PYYFazs9XxcidJn0Q0zl-XZEHWTaWZh_KX72Ym6qS0Y/edit?ref=blockworks&ref=blockworks

can we add functionality by which developer bounties and funds are used towards compound financial products via their comet extensions but on a DevPool UI

I also like that they offer the option of combining multiple protocol actions into one transaction to save on gas fees. that's useful for small bounties for eg. can we do that or integrate with their product to offer "bounty aggregation"?

**Comment by 0x4007** [comment]
> can we add functionality by which developer bounties and funds are used towards compound financial products via their comet extensions but on a DevPool UI

https://t.me/UbiquityDAO/29361/30691

> I also like that they offer the option of combining multiple protocol actions into one transaction to save on gas fees

this sounds like a generic [multicall](https://github.com/mds1/multicall) implementation

---

We can discuss async or on the call if it needs more attention

**Comment by Hodlatoor** [comment]
we can package as a Ubiquity DAO product and DevPool feature , or, integrate compound's as part of a grant proposal.

**Comment by Hodlatoor** [comment]
any other thoughts on how to structure this or go with my original outline?

**Comment by Hodlatoor** [comment]
@pavlovcik @sergfeldman are we proceeding with this or shelving?

**Comment by sergfeldman** [comment]
> @pavlovcik @sergfeldman are we proceeding with this or shelving?

@Hodlatoor At the moment, I do not have enough context regarding the Compound grant to express my opinion.

**Comment by 0x4007** [comment]
I read their document and our offering seems not applicable
