### ISSUE TITLE
DevPool site + dapp

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/research#37]
I'm thinking in terms of showcasing bounties and projects it would be good to have a website (and dapp) that funnels all the info from GitHub as well as our own data and that would also have user logins via their wallets where they can then use partner financial products for their earnings.  

have a nice stats dashboard 

bounty search feature

"suggested" bounties (Via ubiquibot)

a finance section that shows partner products where users can earn on their income (and we benefit as providers or offer our own services)

not only is it a full-fledged platform at this point, it visually showcases a deeper ecosystem and value-added for participants as well as giving us more space for different grant integrations and opportunities.

 a thought for consideration.

**Comment by sergfeldman** [comment]
I support the creation of a separate website for the DevPool for non-crypto partners.

**Comment by 0x4007** [comment]
Soon™️ 

The smart thing to do would be to make a deal with another site like Rethinkable.xyz to build the UI and read our data. 

Right now all of our development resources are still building out key infrastructure. A new UI comes last. 

So to make this actionable:

- [ ] Identity prospective partners
- [ ] Spec out views on dApp
- [ ] Pitch prospective partners

**Comment by 0x4007** [comment]
Duplicate https://github.com/ubiquity/research/issues/50
