### ISSUE TITLE
bounty hunter user data

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/research#38]
aggregating user submitted data like experience, preferences, what they are looking for etc

then applying a matching system and developing a repository of CVs and resumes. 

can be used down the road for head hunting and referral services.

**Comment by 0x4007** [comment]
This is anti crypto ethos to dox. I don't think it's a good idea at this stage, in this industry, especially given our target demographic (devs)

It's very rare to find a doxxed contributor, for example.

**Comment by Hodlatoor** [comment]
anonymise if needed but I think If the system can pull together all this data and provide projects with automatic optimal results it's a big win.

**Comment by 0x4007** [comment]
CVs [pollute data integrity](https://github.com/ubiquity/research/issues/43#issuecomment-1683046096) and will make our matchmaking system less effective

**Comment by Hodlatoor** [comment]
I think it's a missed opportunity to not collect additional data.

**Comment by pavlovcik** [comment]
> aggregating user submitted data like experience, preferences, what they are looking for etc

We can ask them to update their GitHub bios, and parse it for matchmaking, eventually.
