### ISSUE TITLE
Discuss how to engage bounty hunters to introduce us to partners 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#41]

**Comment by Hodlatoor** [comment]
what's a scenario? a Bounty Hunter (BH) works closely on another project we want to know and how do we find out which projects the BH might be able to bring into the conversation for us?

I think this goes back to picking up profiles on our BH. like a CV and then we can search / target for pin point conversations.
If we are looking for wider approach, we can / should have the ability to shot "fireworks" to all BH. think of a firework like a special notice/bounty.  "Do you work with Gnosis and know the dev leads? Earn a bounty right now."

*This is where having an app with push capability would be great.

**Comment by sergfeldman** [comment]
Tested in the DevPool group https://t.me/UbiquityDevPool/2682

**Comment by Hodlatoor** [comment]
should gameify this.
@pavlovcik are you on this? I can put some more thoughts to applying this otherwise.

**Comment by 0x4007** [comment]
I'm distributing in our infra you can see the linked pull requests. I just need to play with the messaging during implementation. You can post ideas here or on those pull requests

**Comment by 0x4007** [comment]
> ### [**[ CLAIM 12.5 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTI1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI0MDk2Mjk4MjUzNzIyNzIwMzkzMTkzNTAwODcyNjYzOTI2Njg0MjY0MTQ2MDI0Nzc2NjAzODgwODU5MjYzNjk3NDQ3MDY3MDI0NTc4OSIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjEyNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHhmOWM2NGM4YjE4NDMzNDRmZTE0NmU0NjJjMmExMjMxZmU3MGI5ZmM1ZmQxOTE4ODRkMzFkNjg4MmQ5YzIxZDkxMjdhNWZiOGMyNzNhYzU2M2FmMGY4ZTY1MGI2M2Q0ZjZjZTczNDFjZDkzZGM4MjAzNzMyNTJiNTc0Zjg3MDNjYzFjIn0=&network=100)
> `0x4007CE208...C149a341d`
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

lol wow epic it merged and loaded the code instantly.
