### ISSUE TITLE
Brainstorm on effective participation in the Ethcon Korea 2023

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#42]
- Discuss the proposal created by @diamondnegroni
https://github.com/ubiquity/business-development/pull/42/files

- Brainstorm on effective participation

**Comment by Hodlatoor** [comment]
@pavlovcik let's discuss dates and activities for me to be there. need to book in advance.

**Comment by sergfeldman** [comment]
### To get a drink 

Following and putting a star to our repo checked by UbiquiBot 

**To get a free drink a participant must**
1. Follow the organization https://github.com/ubiquity/
2. Star the repo https://github.com/ubiquity/devpool-directory

---

@diamondnegroni Please review the proposed T-shirt flow 

Use the T-shirt as a simulation of the task delegation and completion of the DevPool. 

### To order a T-shirt 

**1. We should**
- Create the UbiquiShirt Ethcon 2023 repo
- Setup the issue template 

**2. A participant should** 
- File an issue with the T-shirt title and following issue template 
- Set tags Priority and Time

**3. We should**
- A person delivering the T-shirt assigns himself, gives a T-shirt, educates, and asks to close the issue. 

**4. A participant should** 
- Close the issue

**Comment by 0x4007** [comment]
> To order a T-shirt
> 1. We should
> - Create the UbiquiShirt Ethcon 2023 repo

https://github.com/ubiquity/ubiquibar/issues

> Setup the issue template

https://github.com/ubiquity/ubiquibar/issues/new/choose

<img width="454" alt="image" src="https://github.com/ubiquity/research/assets/4975670/50a88778-cb7e-4e3e-b514-d307764c1f4b">

https://github.com/ubiquity/ubiquibar/blob/development/.github/ISSUE_TEMPLATE/ubiquishirt-order-wizard.yml?plain=1

<img width="953" alt="image" src="https://github.com/ubiquity/research/assets/4975670/52e3a846-0d2e-4fbf-bedc-b742ebc5afcc">

https://github.com/ubiquity/ubiquibar/issues/new?assignees=&labels=&projects=&template=ubiquishirt-order-wizard.yml&title=UbiquiShirt+Order+Request+Wizard

**Comment by diamondnegroni** [comment]
Alex showed it to me last week so I will share this info with the bartenders !
