### ISSUE TITLE
Plan business development for the near future

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#44]
Currently, we are interested in the participation in the Ethcon, establishing partnerships with Safe (and then other b2b partners).

We should effectively plan our business development because both these streams are important and time consuming.

**On the research meeting it would be good:**

1. Define top priority streams for the near future.
Can we focus on these 2 streams till September 2023, or not?

2. Determine our goals, high-level vision on activities and resources needed for each stream.

3. Select leaders of each stream.

**Asynchronously after the research meeting:**

- Plan next steps and timing with each leader.

**Comment by 0x4007** [comment]
> Can we focus on these 2 streams till September 2023, or not? 

I think that core partnership development will run in perpetuity until it's completed. There isn't really a way around getting these strategic partners on board.
