### ISSUE TITLE
Analyze Gnosis launches Visa card that lets you spend self-custody crypto

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#47]
**Gnosis launches Visa card that lets you spend self-custody crypto**

> Gnosis Card is a Visa card that allows users to spend their funds from self-custodial wallets anywhere the payment method is accepted.
The Gnosis Card is initially launching in the U.K. and the EU, with plans to expand to Brazil, Mexico, Singapore and Hong Kong.
Gnosis is also launching Gnosis Pay, a set of developer tools that allow crypto wallets to create a version of their Gnosis Card for users without having to jump through all the hoops of building an online payments system.
https://techcrunch.com/2023/07/17/gnosis-has-a-visa-card-that-lets-you-spend-self-custodial-crypto-in-europe-soon-us-and-hong-kong/

>The team at Gnosis Pay has had talks with wallets that are keen to use their infrastructure to offer similar products to the Gnosis Card.
"We are currently signing letters of intent with multiple wallets," Ernst continued. "Every single one we've spoken to so far has been supremely interested. It is likely the first ones are going to be Zerion and Bankless—1Inch are also top of the list."
https://decrypt.co/148844/crypto-wallet-provider-gnosis-launches-self-custodial-debit-card

**Analyze and define the next steps** 

- Is this changes anything in our plans?
- Should we apply to Gnosis Pay?

**Comment by 0x4007** [comment]
Conclusion is to wait til we try it out before changing any strategy. 

We should definitely apply

**Comment by 0x4007** [comment]
Don't forget to apply when possible @sergfeldman
