### ISSUE TITLE
Communicate progress with Gnosis and define next steps 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#53]
### Gnosis podcast 

The previous episodes are here 
https://open.spotify.com/show/3FghHWrqWr66faGcUeCwtE

Alex can be interviewed for the Gnosis podcast as we use Gnosis Chain to pay freelancers.
I strongly recommend that Alex lead the conversation for this podcast because 
- he initiated the cooperation with Gnosis
- he is the founder 
- he is a great speaker

This is a good opportunity to 
- Offer DevPool for Gnosis, Safe, and all the Open Source projects in the Gnosis ecosystem 
- Express all the wishes for cooperation with Gnosis ecosystem 
We can compile points for cooperation with Gnosis beforehand if it is needed. 

### Gnosis Pay 

Summary of the discussions with the Gnosis Pay team.

- After several contact attempts, I got the chat with Gnosis Pay in Telegram.
- Initially, I requested Ubiquity cards issuing: 
"Be one of the first partners to test the card-issuing solution and give constructive feedback"
- Gnosis Pay offer for other companies is not formed yet. They promised to keep us informed
- Then I offered our DevPool help to develop Gnosis Pay itself.
"Use the Ubiquity bounties marketplace for scaling Gnosis Pay development. 
We offer help in developing the features that we need."

**Comment by sergfeldman** [comment]
The decisions
1) Continue our research and monitor the Gnosis Pay progress.
2) Ask Jon to speak on Gnosis Builders podcast.

**Comment by sergfeldman** [comment]
@pavlovcik @Hodlatoor please, review 

### Proposal of content for the Gnosis podcast

I propose to keep simple info regarding technical aspects and features:
1) DevPool is a bounty marketplace natively built on top of GitHub.
2) All payouts are performed on the Gnosis Chain.
3) DevPool automates routine activity and saves time both for projects and freelancers.
If you are interested, please contact us [here should be our contacts].

The most important: it is needed to express all our requests for collaboration with Gnosis ecosystem.

1) DevPool - we can launch Gnosis and Safe bounties to our marketplace without additional fees.
We can launch any other partner project to our bounties marketplace as well, fees will be discussed with each project.
For the priority partner projects, we can customize DevPool for each partner needs, so that they have their own bounties shop on GitHub.

2) Ubiquity has a proposal for the Safe grant.
[Here should be Jon's idea :) ]

3) We want to issue Ubiquity Card based on the Gnosis Pay and Gnosis Card.

4) Ubiquity wishes to establish a strategic partnership with Gnosis so open to other collaboration options as well.

**Comment by Hodlatoor** [comment]
@sergfeldman 
what was the feedback to :
"Then I offered our DevPool help to develop Gnosis Pay itself."?



still thinking about what the most effective offer to them would be...

**Comment by sergfeldman** [comment]
> @sergfeldman what was the feedback to : "Then I offered our DevPool help to develop Gnosis Pay itself."?
> 
> still thinking about what the most effective offer to them would be...

@Hodlatoor The guys from Gnosis Pay have not reacted to this proposal. I will ping them in some time.

But Gnosis Pay is just one part of Gnosis.

**Comment by Hodlatoor** [comment]
@pavlovcik @sergfeldman I think the value proposition to them is a wider audience for their products which we piggyback into our product offering like each person on DevPool gets a gnosis safe built in. using gnosis chain for payment, any other value propositions to them?

I think looking to UbiquiStreams, yield and staking products should also be on the table.

**Comment by sergfeldman** [comment]
> I think looking to UbiquiStreams, yield and staking products should also be on the table.

@Hodlatoor Per my understanding, everything related to payments is highly relevant to their strategy.
Yield products can be relevant to Safe.

This is a question to Alex could we offer such products or not.

@sergfeldman agreed.  
@pavlovcik - thoughts?

**Comment by 0x4007** [comment]
### Directly relevant Gnosis products:

1. Safe for partners to custody the funds that the UbiquiBot pays to their community. 
2. CowSwap for enhancing the cash out experience. 

### Possibly relevant:

3. Pay. We want to make a card and fiat banking for our users. But if Pay ends up being perfect then we don't need to reinvent it. Again we should wait to actually use their offering before changing our strategy.

**Comment by Hodlatoor** [comment]
great! :)
