### ISSUE TITLE
Decide on application to Visa Accelerator Africa

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#55]
We were informed that we can apply to Visa Accelerator Africa.
https://africa.visa.com/visa-everywhere/innovation/visa-accelerator.html

Accelerator provides 3-months program with an opportunity to connect with mentors, learn more about Visa products, and be considered for investment opportunities.
Applications close on the 25th of August.

Questions:
- Are we ready to actively participate in the accelerator for 3 months?

**Comment by sergfeldman** [comment]
### Questions for Visa Africa Fintech Accelerator

Name of your startup?

What is your company website? 

When was your startup founded? 

Where is your startup’s HQ based? 

What other countries does your startup operate in? 

Do you have a pre existing relationship with Visa? 

How many co-founders are in the founding team? 

Please provide us with your information:  
First name *
Last name *
Phone number *
Email *

What is your title or role within the team? 

What is your personal Linkedin URL? 

Please tell us in two to four sentences about the most impressive thing other than this startup that each founder has built or achieved? 
Please limit your response to 500 characters

How did you find out about this program? (dropdown)

What motivated you to apply for this program? 
Please limit your response to 500 characters

For you to consider this program a success what would your team want to achieve over the program duration?
Please limit your response to 500 characters

What problem are you solving?
Please limit your response to 500 characters

Why did you pick this idea to work on? Do you have domain expertise in this area? 
Please limit your response to 500 characters

Who is your target customer? 
Please limit your response to 250 characters

What is your primary sales model? (dropdown)

Through what channels are you currently engaging these customers? 
Please limit your response to 250 characters

What do you consider the key differentiating factors of your product vs. the competition? 
Please limit your response to 500 characters

Have you deployed your solution with any banks or large corporations? (dropdown)

Which of the following themes does your startup address? 
Choose as many as you like
A Unlocking New Payment Flows: Funds disbursements, Virtual payments credentials, Supply chain payments, supplier onboarding and KYC, Treasury/Payment-as-a-Service & Payment infrastructure enablers
B Embedded Finance: Installments and flexible financing models, Consumer loyalty and rewards, Pre-and-post transaction engagement, Authentication solutions, Banking/Fintech-as-a-Service, B2B platform enablers
C Empowering merchants and SMEs: Next-generation omni-channel and face-to-face payments, Installments, credit scoring, POS financing, BNPL, Digital onboarding for financial services, Seller onboarding and KYC solutions, Merchant loyalty and engagement
D The future of finance: AI powered payments solutions, Blockchain and Enterprise DLT, Decentralized Finance, Open Banking
E Sustainable and Inclusive Finance: Financial education, Carbon footprint / carbon neutral, Sustainable finance / commerce / payment cards, Impact management and measurement, Impact Investing, Financial support services for AgTech
F Payment Infrastructure Enablers: Authentication and fraud solutions, KYC, customer onboarding and identity management, Payment processing and facilitation, B2B platform enablers, Credit scoring and risk management solutions, Data solutions and insights
G Other

What stage is your company? (dropdown)

How many full-time employees do you currently have? (dropdown)

How much equity does the founding team hold? 
As a percentage

How much did you raise in your last round? (In USD) 

At what valuation did you raise your last round at? Please specify if it was not a priced round
Please limit your response to 250 characters

What investors did you bring on in your last round? 
Please limit your response to 250 characters


What is your current primary revenue model? 
A Subscription
B Transactional (direct and web)
C Service-based
D Ad-based
E Commission-based
F Interest-based
G Freemium
H Donations
I License-based (SaaS)
J Other

Has your start-up generated revenue since inception?  (dropdown)


What is your current monthly burn rate? 
In USD

Is your startup incorporated? 

Please attach your company’s incorporation document: 

Are you planning on getting or do you have any regulatory licenses? (dropdown)

Are you currently working under another company’s license? (dropdown)

Please upload the latest copy of your pitch-deck below: 
Please make sure to upload a file below 10 MB, you can use your preferred tool to compress your file if needed or use the following link - https://smallpdf.com/pdf-tools

**Comment by sergfeldman** [comment]
@pavlovcik @Hodlatoor Please, review the terms of the Visa Africa Fintech Accelerator

- The program is completely free of charge for the participating companies and there is NO fee associated with taking part in the activities throughout the cohort.

- All Seed to Series A startups that are post MVP and operating in Africa are encouraged to apply for the program.

- Unlike VEI which is a global startup competition, the Visa Africa Accelerator is a full 3-months program with more engagement and requirements. In this program, the selected startups will be required to meaningfully engage across the tailored mentorship, training, and exercise sessions over a period of 3-months.

- The program will be delivered in a hybrid format and will last for 3-months in total. It will include an onboarding week, 10 virtual focus weeks, an investor week and an in-person Demo Day. Other in-person events maybe be organized during the duration of the program such as city meetups or other country or regional events.

- Visa will cover flights and accommodation for a single founder from each of the participating startups to be able to attend the Demo Day in person.

- Visa Accelerator Program for Africa Application Terms & Conditions (“Terms”)
https://africa.visa.com/content/dam/VCOM/regional/cemea/genericafrica/visa-everywhere/innovation/accelerator/visa-accelerator-terms-conditions.pdf

**Comment by Hodlatoor** [comment]
@sergfeldman , interesting find.  this part is iffy:

![Screenshot_20230815_085625_Samsung Notes.jpg](https://github.com/ubiquity/research/assets/121923660/7c4122c5-bfac-4a56-96f0-14d3beeda5c4)

**Comment by sergfeldman** [comment]
> @sergfeldman , interesting find. this part is iffy:
> 
> ![Screenshot_20230815_085625_Samsung Notes.jpg](https://user-images.githubusercontent.com/121923660/260609136-7c4122c5-bfac-4a56-96f0-14d3beeda5c4.jpg)

@Hodlatoor thank you for noticing.
It can be a blocker because we are not incorporated or registered in one of the markets in Africa.

**Comment by Hodlatoor** [comment]
@sergfeldman  Yes I think it precludes us

**Comment by sergfeldman** [comment]
@pavlovcik Please advise on what to do. 

You said that Visa is one of the TOP priority partners for us.
Participation in the Visa accelerator is a good rare opportunity.
I am not sure that a similar opportunity will appear in 2023.

Since we are not represented in Africa, maybe it is possible to find a partner in Africa and apply TOGETHER with them.
Potentially, I can talk to https://getanchor.co/ about this.

**Comment by Hodlatoor** [comment]
What's the deadline for this? I am trying to see about setting up an entity
in one of the African countries as an option.  messaged my contact. hopefully get a reply soon.

**Comment by sergfeldman** [comment]
> Applications close on the 25th of August.

@Hodlatoor Thank you!
Applications close on the 25th of August.

**Comment by sergfeldman** [comment]
> What's the deadline for this? I am trying to see about setting up an entity
in one of the African countries as an option

@Hodlatoor Thank you! Applications close on the 25th of August.

**Comment by Hodlatoor** [comment]
> > What's the deadline for this? I am trying to see about setting up an entity
> in one of the African countries as an option
> 
> @Hodlatoor Thank you! Applications close on the 25th of August.
> 
> 

next week. 😂

**Comment by 0x4007** [comment]
It seems like it's a bit of a stretch if they are aiming for African founders. 

Who's going to Africa for the in person stuff? I'm really not keen on it. I don't hear the greatest things about visiting 👀 

But yes it's true, developing a relationship with Visa is top strategic benefit for us, if that allows us to integrate into the fiat banking system by means of Visa debit cards.

**Comment by Hodlatoor** [comment]
it's a stretch. time too constrained but spun the wheel on African
entities. haven't heard back much so far. And right now there's a bit of
strife going on. for eg going to south africa now is not advisable.

**Comment by sergfeldman** [comment]
Thank you for the input!
I will close this issue

**Comment by 0x4007** [comment]
Actually, yeah, technically we decided (no) on the application
